In [1]:
import numpy as np

In [2]:
a=np.array(50)
print(a)



50


In [3]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [5]:
print(c)
print(c.shape)
c.shape=(2,3)
print(c)



[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
d=np.arange(20)
print(d)
print(d[5])
print(d[5:19])
print(d[:7])
print(d[9:])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
5
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[0 1 2 3 4 5 6]
[ 9 10 11 12 13 14 15 16 17 18 19]


In [7]:
import numpy as np
e=np.array([1,2,3,'abc','sai'])
print(e)
print(e[1:4])



['1' '2' '3' 'abc' 'sai']
['2' '3' 'abc']
